---
- name: Set up Apache virtuahHost
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/{{ http_conf }}
    owner: apache
    group: apache
    mode: 0644
    


- name: copying function. php to the webserver
  template:
   src: function.php.j2
   dest: /var/www/html/tooling/html/{{ templating_functions }}
   owner: root
   group: root
   mode: 0600

  notify: restart httpd service




